# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatabaseDine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatabaseDine
	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    
  target 'DatabaseDineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatabaseDineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
